### ISSUE TITLE
Type errors on master

### ISSUE THREAD

**Issue by felixfbecker** [codecov/sourcegraph-codecov#28]
On master, `yarn run typecheck` prints these errors:

```
> yarn run typecheck
yarn run v1.16.0
$ tsc -p tsconfig.json
src/model.ts:18:9 - error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.

18         baseURL: endpoint.url,
           ~~~~~~~

  src/api.ts:7:5
    7     baseURL: string
          ~~~~~~~
    The expected type comes from property 'baseURL' which is declared here on type 'CodecovGetCommitCoverageArgs'

src/model.ts:31:9 - error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.

31         baseURL: endpoint.url,
           ~~~~~~~

  src/api.ts:7:5
    7     baseURL: string
          ~~~~~~~
    The expected type comes from property 'baseURL' which is declared here on type 'CodecovGetCommitCoverageArgs'

src/model.ts:44:9 - error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.

44         baseURL: endpoint.url,
           ~~~~~~~

  src/api.ts:7:5
    7     baseURL: string
          ~~~~~~~
    The expected type comes from property 'baseURL' which is declared here on type 'CodecovGetCommitCoverageArgs'

src/model.ts:49:39 - error TS2345: Argument of type 'unknown' is not assignable to parameter of type '{ l: { [line: number]: string | number | null | undefined; }; t: { c: string; }; } | undefined'.
  Type 'unknown' is not assignable to type '{ l: { [line: number]: string | number | null | undefined; }; t: { c: string; }; }'.

49         const ratio = toCoverageRatio(fileData)
                                         ~~~~~~~~

src/uri.test.ts:11:50 - error TS2554: Expected 1 arguments, but got 2.

11             assert.throws(() => resolveURI(null, 'file:///d/f')))
                                                    ~~~~~~~~~~~~~

src/uri.test.ts:15:34 - error TS2554: Expected 1 arguments, but got 2.

15                 resolveURI(null, 'git://example.com/repo?v#d/f'),
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/uri.test.ts:27:53 - error TS2554: Expected 1 arguments, but got 2.

27                 resolveURI({ repo: 'r', rev: 'v' }, 'file:///d/f'),
                                                       ~~~~~~~~~~~~~

src/uri.test.ts:39:21 - error TS2554: Expected 1 arguments, but got 2.

39                     'git://example.com/repo?v#d/f'
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/uri.test.ts:52:21 - error TS2554: Expected 1 arguments, but got 2.

52                     'git://example.com/repo2?v2#d/f'
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/uri.test.ts:63:46 - error TS2554: Expected 1 arguments, but got 2.

63         assert.throws(() => resolveURI(null, 'example://a')))
                                                ~~~~~~~~~~~~~

src/uri.ts:41:15 - error TS2322: Type 'readonly Endpoint[] | undefined' is not assignable to type 'Endpoint[] | undefined'.
  The type 'readonly Endpoint[]' is 'readonly' and cannot be assigned to the mutable type 'Endpoint[]'.

41         const endpoints: Endpoint[] | undefined = sourcegraph.configuration.get<Settings>().get('codecov.endpoints')
                 ~~~~~~~~~


Found 11 errors.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

@3askaal these seem to have been introduced in #19

**Comment by felixfbecker** [comment]
It would be a good idea to add CI to this repo
